### ISSUE TITLE
DataForSendToPrinterTSC is not defined

### ISSUE THREAD

**Issue by mkonecny** [ThinhVu/tsc-printer-js#5]
```
(node:3236144) UnhandledPromiseRejectionWarning: ReferenceError: DataForSendToPrinterTSC is not defined
    at Object.bitmap (/home/martin/workspace/tsc-printer-js/src/TscBuffer.js:148:17)
    at printImage (/home/martin/workspace/tsc-printer-js/examples/index.js:14:34)
```

Cannot find this defined anywhere in the library even though it is being referenced

**Comment by ThinhVu** [comment]
> ```
> (node:3236144) UnhandledPromiseRejectionWarning: ReferenceError: DataForSendToPrinterTSC is not defined
>     at Object.bitmap (/home/martin/workspace/tsc-printer-js/src/TscBuffer.js:148:17)
>     at printImage (/home/martin/workspace/tsc-printer-js/examples/index.js:14:34)
> ```
> 
> Cannot find this defined anywhere in the library even though it is being referenced

Sorry for the very late answer. The file has been replaced with TscBuffer.js

**Comment by mkonecny** [comment]
Thank you @ThinhVu !
